# Generated by Django 4.2.14 on 2024-07-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="category",
            field=models.CharField(
                choices=[("G", "GOLD"), ("S", "SILVER"), ("B", "BRONZE")],
                default="B",
                max_length=1,
            ),
        ),
    ]
