# Generated by Django 4.2.14 on 2024-07-28 22:11

from django.db import migrations, models
import user.enums


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_category_alter_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="category",
            field=models.SmallIntegerField(
                choices=[(3, "GOLD"), (2, "SILVER"), (1, "BRONZE")],
                default=user.enums.UserCategory["BRONZE"].value,
            ),
        ),
    ]
