version: '3.9'

volumes:
  database-data:

services:
  database:
    image: postgres:11.22-alpine
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
      timeout: 5s
