# Generated by Django 4.2.14 on 2024-07-27 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created", models.DateTimeField(auto_now_add=True)),
                ("_updated", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("final_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "PENDING"), ("S", "SHIPPED"), ("C", "CANCELED")],
                        default=order.enums.OrderStatus["PENDING"].value,
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "order",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProductDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created", models.DateTimeField(auto_now_add=True)),
                ("_updated", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=31, null=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "ACTIVE"), ("I", "INACTIVE")],
                        default=order.enums.DiscountStatus["ACTIVE"].value,
                        max_length=1,
                    ),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=10)),
                ("remaining_uses", models.IntegerField(default=1)),
                ("deadline", models.DateTimeField(null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.department",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_discount",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created", models.DateTimeField(auto_now_add=True)),
                ("_updated", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=31, null=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "ACTIVE"), ("I", "INACTIVE")],
                        default=order.enums.DiscountStatus["ACTIVE"].value,
                        max_length=1,
                    ),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=10)),
                ("remaining_uses", models.IntegerField(default=1)),
                ("deadline", models.DateTimeField(null=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("I", "INTERNAL_STAFF"), ("E", "EXTERNAL_CUSTOMER")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "user_category",
                    models.CharField(
                        choices=[("G", "GOLD"), ("S", "SILVER"), ("B", "BRONZE")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_discount",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UsedDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created", models.DateTimeField(auto_now_add=True)),
                ("_updated", models.DateTimeField(auto_now=True)),
                ("cancelled", models.BooleanField(default=False)),
                (
                    "product_discount",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.productdiscount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_discount",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.userdiscount",
                    ),
                ),
            ],
            options={
                "db_table": "used_discount",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created", models.DateTimeField(auto_now_add=True)),
                ("_updated", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("final_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.useddiscount",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "order_item",
                "managed": True,
            },
        ),
    ]
