# Generated by Django 4.2.14 on 2024-07-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdiscount",
            name="user_category",
        ),
    ]
