# Generated by Django 4.2.14 on 2024-07-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_remove_userdiscount_user_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdiscount",
            name="user_category",
            field=models.SmallIntegerField(
                choices=[(3, "GOLD"), (2, "SILVER"), (1, "BRONZE")], default=1
            ),
        ),
    ]
