# Generated by Django 4.2.14 on 2024-07-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_userdiscount_user_category_by_integer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="discount",
        ),
    ]
