# Generated by Django 4.2.14 on 2024-07-29 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_useddiscount_order_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useddiscount",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="order.orderitem",
            ),
        ),
    ]
